/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <cstrike>
#include <csx>

#define PLUGIN 	"C4 Timer and Sound"
#define VERSION "2.8"
#define AUTHOR 	"Google Genemi, kwpd"

#define TASK_SOUND_BASE 6900
#define MAX_SPRITES 2

// Constante base para el ScreenFade (1<<12 = 4096 unidades = 1 segundo)
#define FADE_SECOND (1<<12) 

new g_c4timer
new cvar_showteam, cvar_flash, cvar_sprite, cvar_msg, g_Cvar, g_C4, pcvarToggle
new g_msg_showtimer, g_msg_roundtime, g_msg_scenario, g_msg_screenfade

new const g_timersprite[MAX_SPRITES][] = { "bombticking", "bombticking1" }
new const g_message[] = "Detonation time initialized..."

new g_plant_index = 0

// Sonidos al plantar la bomba
new const g_plant_sounds[][] = {
	"C4timer/plant1.wav",
	"C4timer/plant2.wav",
	"C4timer/plant3.wav",
	"C4timer/plant4.wav"
}

// Matriz organizada por idioma [Voice_ID][Segundos (0 a 9 -> representa 1 a 10)]
new const C4Sonidos[3][10][] = {
	{ "C4timer/english_man/EN01.wav", "C4timer/english_man/EN02.wav", "C4timer/english_man/EN03.wav",
		"C4timer/english_man/EN04.wav", "C4timer/english_man/EN05.wav", "C4timer/english_man/EN06.wav",
		"C4timer/english_man/EN07.wav", "C4timer/english_man/EN08.wav", "C4timer/english_man/EN09.wav",
		"C4timer/english_man/EN10.wav"
	},
	{ "C4timer/english_women/EN01.wav", "C4timer/english_women/EN02.wav", "C4timer/english_women/EN03.wav",
		"C4timer/english_women/EN04.wav", "C4timer/english_women/EN05.wav", "C4timer/english_women/EN06.wav",
		"C4timer/english_women/EN07.wav", "C4timer/english_women/EN08.wav", "C4timer/english_women/EN09.wav",
		"C4timer/english_women/EN10.wav"
	},
	{ "C4timer/spanish/ES01.wav", "C4timer/spanish/ES02.wav", "C4timer/spanish/ES03.wav",
		"C4timer/spanish/ES04.wav", "C4timer/spanish/ES05.wav", "C4timer/spanish/ES06.wav",
		"C4timer/spanish/ES07.wav", "C4timer/spanish/ES08.wav", "C4timer/spanish/ES09.wav",
		"C4timer/spanish/ES10.wav"
	}
}

public plugin_init()
{
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	cvar_showteam	= register_cvar("amx_showc4timer", "3")
	cvar_flash	= register_cvar("amx_showc4flash", "1")
	cvar_sprite	= register_cvar("amx_showc4sprite", "1")
	cvar_msg	= register_cvar("amx_showc4msg", "1")
	
	pcvarToggle	= register_cvar("C4_voice", "1")
	g_Cvar		= register_cvar("amx_soundc4", "1")
	
	g_msg_showtimer  = get_user_msgid("ShowTimer")
	g_msg_roundtime  = get_user_msgid("RoundTime")
	g_msg_scenario   = get_user_msgid("Scenario")
	g_msg_screenfade = get_user_msgid("ScreenFade")
	
	register_event("HLTV", "event_hltv", "a", "1=0", "2=0")
	register_logevent("StopSoundTasks", 2, "1=Round_End")
	register_logevent("StopSoundTasks_next", 2, "1=Round_Start")
	register_logevent("logevent_plantedthebomb", 3, "2=Planted_The_Bomb")
	
	g_C4 = get_cvar_pointer("mp_c4timer")
}

public plugin_precache()
{
	static szPath[128]
	
	// Precache optimizado de las voces
	for(new v = 0; v < sizeof(C4Sonidos); v++)
	{
		for(new s = 0; s < sizeof(C4Sonidos[]); s++)
		{
			// Verificar si existe el archivo en la carpeta 'sound/' antes de precashearlo
			formatex(szPath, charsmax(szPath), "sound/%s", C4Sonidos[v][s])
			
			if(file_exists(szPath))
			{
				precache_sound(C4Sonidos[v][s])
			}
			else
			{
				log_amx("[C4 Timer] Advertencia: Archivo no encontrado '%s'", szPath)
			}
		}
	}
	
	// Precache optimizado de los sonidos de plantado
	for(new p = 0; p < sizeof(g_plant_sounds); p++)
	{
		formatex(szPath, charsmax(szPath), "sound/%s", g_plant_sounds[p])
		
		if(file_exists(szPath))
		{
			precache_sound(g_plant_sounds[p])
		}
		else
		{
			log_amx("[C4 Timer] Advertencia: Archivo no encontrado '%s'", szPath)
		}
	}
}

public event_hltv()
{
	g_c4timer = get_pcvar_num(g_C4)
}

public logevent_plantedthebomb()
{
	new showteam = get_pcvar_num(cvar_showteam)
	static players[32], num
	
	switch(showteam)
	{
		case 1: get_players(players, num, "ae", "TERRORIST")
		case 2: get_players(players, num, "ae", "CT")
		case 3: get_players(players, num, "a")
		default: return
	}
	
	for(new i = 0; i < num; ++i)
	{
		new id = players[i]
		set_task(1.0, "update_timer", id)
		
		if(get_pcvar_num(cvar_flash))
		{
			flash_user_screen(id, 255, 100, 0, 70, FADE_SECOND / 2, FADE_SECOND / 2)
		}
	}
}

public update_timer(id)
{
	if(!is_user_connected(id) || !is_user_alive(id)) return
	
	message_begin(MSG_ONE_UNRELIABLE, g_msg_showtimer, _, id)
	message_end()
	
	message_begin(MSG_ONE_UNRELIABLE, g_msg_roundtime, _, id)
	write_short(g_c4timer)
	message_end()
	
	message_begin(MSG_ONE_UNRELIABLE, g_msg_scenario, _, id)
	write_byte(1)
	write_string(g_timersprite[clamp(get_pcvar_num(cvar_sprite), 0, (MAX_SPRITES - 1))])
	write_byte(150)
	write_short(get_pcvar_num(cvar_flash) ? 20 : 0)
	message_end()
	
	if(get_pcvar_num(cvar_msg))
	{
		set_hudmessage(255, 180, 0, 0.44, 0.87, 2, 6.0, 6.0)
		show_hudmessage(id, g_message)
	}
}

public bomb_planted(planter)
{
	if(!get_pcvar_num(g_Cvar))
		return PLUGIN_CONTINUE
	
	new Float:c4time = get_pcvar_float(g_C4)
	
	for(new i = 10; i >= 1; i--)
	{
		new Float:delay = c4time - float(i)
		if(delay >= 0.0)
		{
			set_task(delay, "play_countdown_sound", TASK_SOUND_BASE + i)
		}
	}
	
	// Reproduce el sonido actual según el índice secuencial
	client_cmd(0, "spk %s", g_plant_sounds[g_plant_index])
	
	// Incrementa el índice y lo reinicia a 0 si llega al total de sonidos (4)
	g_plant_index++
	if(g_plant_index >= sizeof(g_plant_sounds))
	{
		g_plant_index = 0
	}
	
	return PLUGIN_CONTINUE
}

public bomb_explode(planter, defuser)
{
	StopSoundTasks()
	
	static players[32], num
	get_players(players, num, "a")
	
	for(new i = 0; i < num; i++)
	{
		flash_user_screen(players[i], 255, 255, 255, 100, FADE_SECOND / 2, FADE_SECOND / 2)
	}
}

public bomb_defused(defuser)
{
	StopSoundTasks()
}

public play_countdown_sound(taskid)
{
	new second = taskid - TASK_SOUND_BASE
	
	new voice = clamp(get_pcvar_num(pcvarToggle) - 1, 0, 2)
	new sound_index = clamp(second - 1, 0, 9)
	
	client_cmd(0, "spk %s", C4Sonidos[voice][sound_index])
}

public StopSoundTasks()
{
	for(new i = 1; i <= 10; i++)
	{
		remove_task(TASK_SOUND_BASE + i)
	}
}

public StopSoundTasks_next()
{
	new num = get_pcvar_num(pcvarToggle);
	
	for(new i = 1; i <= 10; i++)
	{
		remove_task(TASK_SOUND_BASE + i);
	}
	
	switch (num)
	{
		case 1: num = 2;
		case 2: num = 3;
		default: num = 1;
	}
	
	set_pcvar_num(pcvarToggle, num);
}

stock flash_user_screen(id, r, g, b, alpha, duration, holdtime)
{
	message_begin(MSG_ONE_UNRELIABLE, g_msg_screenfade, _, id)
	write_short(duration)
	write_short(holdtime)
	write_short(0x0000)
	write_byte(r)
	write_byte(g)
	write_byte(b)
	write_byte(alpha)
	message_end()
}
